service: default

runtime: python312

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

  - url: /static
    static_dir: static

automatic_scaling:
  min_instances: 1

inbound_services:
  - warmup
